release-date = "2022-02-23"

[[entries]]
id = "823dd444-2c38-471c-ab70-573a82888ef4"
type = "fix"
description = "fix incompatibilities in `nr.util.parsing` and `nr.util.text` for Python 3.7 and 3.8"
author = "@NiklasRosenstein"

[[entries]]
id = "f93c97cf-5256-4187-8255-56a34b405fc3"
type = "feature"
description = "add `nr.util.functional.supplier_get()`"
author = "@NiklasRosenstein"

[[entries]]
id = "25c610f3-c15e-401a-b7f6-f18210a28923"
type = "fix"
description = "add `typing-extensions` as runtime dependency"
author = "@NiklasRosenstein"
