[[entries]]
id = "2cb0aa04-096f-4086-b049-c7a727730899"
type = "feature"
description = "add `Scanner(start_index)` parameter"
author = "@NiklasRosenstein"

[[entries]]
id = "cbaa6890-ba28-4412-ba5f-097f68609efe"
type = "deprecation"
description = "deprecate `Scanner.ensure_advancing()` in favor of `Scanner.safe_iter()`"
author = "@NiklasRosenstein"

[[entries]]
id = "43b33901-a9d8-4bae-8c85-5b3055483d8a"
type = "improvement"
description = "`Scanner.advance()` now returns `T | None`"
author = "@NiklasRosenstein"

[[entries]]
id = "b850e33f-2972-4c39-8590-2993c6715ee7"
type = "deprecation"
description = "move `nr.util.coalesce()` to `nr.util.functional.coalesce()`, the original function is still available but marked as deprecated"
author = "@NiklasRosenstein"

[[entries]]
id = "3525affc-170e-49cd-9f68-0112c79e4bfa"
type = "feature"
description = "add `nr.util.functional.assure()`"
author = "@NiklasRosenstein"
