[[entries]]
id = "4a12d2e4-80ea-48d9-bb29-e49f5a834194"
type = "feature"
description = "add `nr.util.types`"
author = "@NiklasRosenstein"

[[entries]]
id = "a068d2af-2cf2-42e7-9dac-b03246422de8"
type = "fix"
description = "add `sorting_key` parameter to `topological_sort()`"
author = "@NiklasRosenstein"
