# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.x"]
        python-tooling-version: ["3.10.2"]

    steps:
    - uses: actions/checkout@v2

    - uses: gabrielfalcao/pyenv-action@v9
      with:
        default: "${{ matrix.python-tooling-version }}"
        command: |
          pip install -U pip
          pip install pipx
          pipx install poetry==1.2.0a2
          pipx install slam-cli==1.0.0a12

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: slam install --no-venv-check

    - name: Run tests
      run: slam test
